apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: k8s-chatapp 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        name: backend-pod
        namespace: k8s-chatapp
    spec:
      containers:
        - name: backend-chatapp
          image: swapnilmali101/chatapp-backend:latest
          ports:
            - containerPort: 5001
          env:
            - name: MONGODB_URI
              value: "mongodb://swapnil:swapnil123@mongodb:27017/chatapp?authSource=admin"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: jwt-secret
            - name: PORT
              value: "5001"
            - name: NODE_ENV
              value: "production"
