apiVersion: v1  
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: k8s-chatapp      
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce 
  resources:
    requests: 
      storage: 1Gi