apiVersion: v1
kind: PersistentVolume        
metadata:
  name: mongodb-pv
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce 
  hostPath:
    path: /data/mongodb
    type: DirectoryOrCreate
