apiVersion: v1
kind: Secret    
metadata:
  name: backend-secrets 
  namespace: k8s-chatapp
type: Opaque
data:
  jwt-secret: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjM05UUTROVGs0T0N3aWFXRjBJam94TnpjMU5EZzFPVGc0ZlEuUDNMRTFEeVp2Z0htMUJTZE1DZ1hUNHotYTlleWtqNEphemgwX3dGSlBlUQo=
  
  
  
  
  
  
  